In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [ ]:
dataset.columns

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [5]:
dependent=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train
X_test
Y_train
Y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [8]:
#but this code didnt improve the r2_score. so didnt run this while execution

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','poisson'],
             'max_features':[None,1,0.5,'sqrt','log2'],
             'splitter':['best','random']}

grid=GridSearchCV(DecisionTreeRegressor(),param_grid, refit=True,verbose = 3, n_jobs=-1)

grid.fit(X_train,Y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': [None, 1, 0.5, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
re= grid.cv_results_
#print(re)

print("R2 value for best parameter {}:".format(grid.best_params_))

R2 value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}:

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012075,0.005956,0.003332,0.001245,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.748307,0.534925,0.778275,0.635637,0.659761,0.671381,0.086460,2
1,0.009504,0.003395,0.005006,0.000408,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.652252,0.499567,0.653472,0.483349,0.598733,0.577475,0.073141,22
2,0.010814,0.001297,0.005447,0.000856,squared_error,1,best,"{'criterion': 'squared_error', 'max_features':...",0.486121,0.620938,0.459506,0.375809,0.528672,0.494209,0.080668,28
3,0.009043,0.000615,0.005824,0.001079,squared_error,1,random,"{'criterion': 'squared_error', 'max_features':...",0.745140,0.557422,0.499744,0.377241,0.464627,0.528835,0.122927,26
4,0.012307,0.001348,0.006125,0.000816,squared_error,0.5,best,"{'criterion': 'squared_error', 'max_features':...",0.746333,0.591572,0.729143,0.651389,0.497841,0.643255,0.091525,8
5,0.009176,0.001049,0.005487,0.001166,squared_error,0.5,random,"{'criterion': 'squared_error', 'max_features':...",0.702600,0.574405,0.656577,0.387928,0.582908,0.580883,0.107538,20
6,0.009328,0.000731,0.005538,0.001030,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.619238,0.624776,0.755881,0.693938,0.687541,0.676275,0.050361,1
7,0.008466,0.000484,0.005076,0.000139,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.709746,0.618112,0.610027,0.668207,0.594363,0.640091,0.042709,9
8,0.011529,0.001567,0.004731,0.000802,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.525771,0.498159,0.580675,0.500323,0.652741,0.551534,0.058698,25
9,0.007099,0.000964,0.003521,0.000738,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.682493,0.525809,0.688056,0.546754,0.624622,0.613547,0.067212,14
10,0.075105,0.003910,0.005091,0.001160,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.751319,0.646699,0.609141,0.562349,0.688263,0.651554,0.064932,4
11,0.052516,0.008207,0.005284,0.000764,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.690139,0.577284,0.607984,0.531678,0.647661,0.610949,0.054854,15
12,0.033039,0.007157,0.004400,0.000761,absolute_error,1,best,"{'criterion': 'absolute_error', 'max_features'...",0.734751,0.602574,0.575889,0.461578,0.409825,0.556923,0.113838,23
13,0.024963,0.001733,0.004641,0.000504,absolute_error,1,random,"{'criterion': 'absolute_error', 'max_features'...",0.484327,0.404485,0.240260,0.553431,0.571909,0.450882,0.120662,29
14,0.045648,0.007761,0.004808,0.000714,absolute_error,0.5,best,"{'criterion': 'absolute_error', 'max_features'...",0.712453,0.647857,0.609352,0.545513,0.628586,0.628752,0.054178,10
15,0.036520,0.004498,0.004975,0.000849,absolute_error,0.5,random,"{'criterion': 'absolute_error', 'max_features'...",0.708784,0.646966,0.553048,0.533384,0.627431,0.613923,0.063977,13
16,0.042444,0.004377,0.004481,0.000867,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.685921,0.548630,0.690626,0.577747,0.638847,0.628354,0.056954,11
17,0.037314,0.008457,0.004708,0.000435,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.788459,0.398656,0.599669,0.601587,0.505668,0.578808,0.128617,21
18,0.045007,0.006634,0.004778,0.000434,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.656150,0.497360,0.720040,0.540888,0.589733,0.600834,0.079616,17
19,0.032104,0.005292,0.005783,0.001516,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.603845,0.674760,0.553697,0.622706,0.486836,0.588369,0.063864,19
20,0.016399,0.001080,0.005409,0.000784,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.698522,0.591710,0.694750,0.624394,0.624796,0.646834,0.042416,7
21,0.012793,0.002240,0.004931,0.000830,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.694036,0.718114,0.626623,0.470389,0.608561,0.623545,0.086721,12
22,0.010908,0.001981,0.004758,0.000410,poisson,1,best,"{'criterion': 'poisson', 'max_features': 1, 's...",0.544462,0.330682,0.541840,0.317895,0.385188,0.424013,0.099870,30
23,0.008647,0.002164,0.004625,0.000451,poisson,1,random,"{'criterion': 'poisson', 'max_features': 1, 's...",0.568333,0.364973,0.727047,0.351502,0.547626,0.511896,0.140046,27
24,0.011307,0.000898,0.004520,0.000614,poisson,0.5,best,"{'criterion': 'poisson', 'max_features': 0.5, ...",0.782089,0.597366,0.698842,0.594928,0.565466,0.647738,0.080940,6
25,0.009518,0.001274,0.005017,0.000661,poisson,0.5,random,"{'criterion': 'poisson', 'max_features': 0.5, ...",0.649551,0.541201,0.701657,0.588007,0.536024,0.603288,0.063921,16
26,0.010758,0.001346,0.004255,0.001561,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.697691,0.645182,0.692103,0.654061,0.636531,0.665113,0.025004,3
27,0.008662,0.001911,0.004011,0.001029,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.661788,0.600163,0.541948,0.564641,0.592698,0.592248,0.040475,18
28,0.008099,0.002962,0.003515,0.001500,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.668506,0.642109,0.690962,0.630224,0.607515,0.647863,0.029175,5
29,0.008171,0.001542,0.004718,0.001968,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.599078,0.506491,0.507610,0.657976,0.511378,0.556507,0.061705,24

In [12]:
future_pred=grid.predict([[32,43,2,0,1]])
future_pred

array([46661.4424])