In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [5]:
dependent=dataset[['charges']]

In [8]:
''' since we are using g
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train
X_test
Y_train
Y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [9]:
#but this code didnt improve the r2_score. so didnt run this while execution
'''
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train
'''

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
             'C':[5,20,50,1000,15000],
             'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid, refit=True,verbose = 3, n_jobs=-1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

KeyboardInterrupt:

In [ ]:
re= grid.cv_results_
#print(re)

print("R2 value for best parameter {}:".format(grid.best_params_))

In [16]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.132796,0.004017,0.068751,0.002064,5,auto,rbf,"{'C': 5, 'gamma': 'auto', 'kernel': 'rbf'}",-0.018310,-0.011761,-0.124434,-0.117107,-0.122196,-0.078761,0.052128,37
1,0.100714,0.004362,0.020771,0.000511,5,auto,poly,"{'C': 5, 'gamma': 'auto', 'kernel': 'poly'}",0.008422,0.017429,-0.094517,-0.080840,-0.093399,-0.048581,0.050529,34
2,0.136937,0.003800,0.028978,0.001197,5,auto,sigmoid,"{'C': 5, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.005263,0.021434,-0.095638,-0.089966,-0.094233,-0.050628,0.052519,36
3,0.097072,0.002596,0.018442,0.001095,5,auto,linear,"{'C': 5, 'gamma': 'auto', 'kernel': 'linear'}",0.208436,0.273517,0.114377,0.131742,0.125698,0.170754,0.061173,23
4,0.127373,0.004690,0.062051,0.003427,5,scale,rbf,"{'C': 5, 'gamma': 'scale', 'kernel': 'rbf'}",-0.018277,-0.011815,-0.124402,-0.117128,-0.122193,-0.078763,0.052118,38
5,0.101846,0.001265,0.021606,0.001429,5,scale,poly,"{'C': 5, 'gamma': 'scale', 'kernel': 'poly'}",0.007740,0.018388,-0.095010,-0.080146,-0.093431,-0.048492,0.050637,33
6,0.137485,0.005894,0.027425,0.002324,5,scale,sigmoid,"{'C': 5, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.005111,0.021680,-0.095748,-0.089853,-0.094240,-0.050610,0.052558,35
7,0.098083,0.002141,0.017928,0.001781,5,scale,linear,"{'C': 5, 'gamma': 'scale', 'kernel': 'linear'}",0.208436,0.273517,0.114377,0.131742,0.125698,0.170754,0.061173,23
8,0.130533,0.002545,0.064713,0.002311,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.046078,0.061245,-0.064529,-0.051593,-0.066716,-0.015103,0.056587,31
9,0.097144,0.002986,0.019280,0.001412,20,auto,poly,"{'C': 20, 'gamma': 'auto', 'kernel': 'poly'}",0.145255,0.165639,0.052292,0.080461,0.039547,0.096639,0.050224,26
10,0.138655,0.003047,0.027190,0.002055,20,auto,sigmoid,"{'C': 20, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.127902,0.178414,0.033190,0.045773,0.042295,0.085515,0.057641,30
11,0.106210,0.007827,0.018782,0.000996,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",0.508760,0.595150,0.461139,0.493146,0.464225,0.504484,0.048717,15
12,0.130072,0.001402,0.066509,0.003043,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.046212,0.061027,-0.064425,-0.051699,-0.066708,-0.015118,0.056552,32
13,0.097414,0.004783,0.020907,0.000660,20,scale,poly,"{'C': 20, 'gamma': 'scale', 'kernel': 'poly'}",0.142762,0.168797,0.050661,0.082109,0.039437,0.096753,0.050855,25
14,0.134592,0.004264,0.027645,0.001186,20,scale,sigmoid,"{'C': 20, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.127489,0.179200,0.032881,0.046024,0.042268,0.085572,0.057860,29
15,0.104476,0.011207,0.019339,0.002723,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",0.508760,0.595150,0.461139,0.493146,0.464225,0.504484,0.048717,15
16,0.127661,0.007676,0.059913,0.002572,50,auto,rbf,"{'C': 50, 'gamma': 'auto', 'kernel': 'rbf'}",0.158065,0.186988,0.032774,0.055487,0.039281,0.094519,0.064770,27
17,0.098262,0.003724,0.019963,0.001683,50,auto,poly,"{'C': 50, 'gamma': 'auto', 'kernel': 'poly'}",0.347640,0.384358,0.265003,0.317976,0.237765,0.310548,0.053387,19
18,0.130265,0.007308,0.026215,0.001415,50,auto,sigmoid,"{'C': 50, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.306701,0.411565,0.234930,0.247962,0.246348,0.289501,0.065971,22
19,0.122844,0.019428,0.020513,0.002268,50,auto,linear,"{'C': 50, 'gamma': 'auto', 'kernel': 'linear'}",0.562705,0.639891,0.527991,0.555174,0.523959,0.561944,0.041756,13
20,0.138316,0.017705,0.062319,0.005648,50,scale,rbf,"{'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}",0.158332,0.186476,0.032993,0.055287,0.039299,0.094478,0.064656,28
21,0.114333,0.016118,0.026840,0.013324,50,scale,poly,"{'C': 50, 'gamma': 'scale', 'kernel': 'poly'}",0.343754,0.389372,0.261939,0.321017,0.237569,0.310730,0.054980,18
22,0.133069,0.017821,0.027308,0.002433,50,scale,sigmoid,"{'C': 50, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.305987,0.413027,0.234226,0.248710,0.246294,0.289649,0.066508,21
23,0.112272,0.012161,0.019889,0.001051,50,scale,linear,"{'C': 50, 'gamma': 'scale', 'kernel': 'linear'}",0.562705,0.639891,0.527991,0.555174,0.523959,0.561944,0.041756,13
24,0.152265,0.003266,0.062834,0.002694,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,8
25,0.150292,0.022572,0.020283,0.002329,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,5
26,0.153166,0.007646,0.027936,0.002137,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,20
27,0.141744,0.008818,0.019842,0.001561,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
28,0.157439,0.004325,0.060838,0.001421,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,7
29,0.163247,0.036680,0.021198,0.000696,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,6
30,0.153658,0.007811,0.027948,0.001763,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,17
31,0.144833,0.006677,0.018468,0.001449,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,11
32,0.446854,0.058417,0.061006,0.003042,15000,auto,rbf,"{'C': 15000, 'gamma': 'auto', 'kernel': 'rbf'}",0.837793,0.812317,0.830847,0.825861,0.752682,0.811900,0.030761,2
33,1.085458,0.265568,0.020284,0.001124,15000,auto,poly,"{'C': 15000, 'gamma': 'auto', 'kernel': 'poly'}",0.849423,0.802643,0.816907,0.803667,0.764010,0.807330,0.027479,3
34,0.150848,0.010481,0.026616,0.001436,15000,auto,sigmoid,"{'C': 15000, 'gamma': 'auto', 'kernel': 'sigmo...",-55.436104,-59.922413,-40.175241,-71.297258,-40.117439,-53.389691,11.985988,40
35,0.494910,0.078622,0.019785,0.000339,15000,auto,linear,"{'C': 15000, 'gamma': 'auto', 'kernel': 'linear'}",0.660814,0.581368,0.697918,0.528587,0.655731,0.624883,0.061226,9
36,0.518885,0.100358,0.061484,0.003101,15000,scale,rbf,"{'C': 15000, 'gamma': 'scale', 'kernel': 'rbf'}",0.837880,0.812341,0.830848,0.825856,0.752687,0.811922,0.030774,1
37,1.047026,0.345105,0.013145,0.003765,15000,scale,poly,"{'C': 15000, 'gamma': 'scale', 'kernel': 'poly'}",0.849194,0.802543,0.816898,0.803667,0.764007,0.807262,0.027413,4
38,0.153753,0.006631,0.026747,0.001798,15000,scale,sigmoid,"{'C': 15000, 'gamma': 'scale', 'kernel': 'sigm...",-51.140561,-61.416605,-54.767676,-57.671053,-40.078287,-53.014836,7.296708,39
39,0.487579,0.087157,0.018396,0.002853,15000,scale,linear,"{'C': 15000, 'gamma': 'scale', 'kernel': 'line...",0.660814,0.581368,0.697918,0.528587,0.655731,0.624883,0.061226,9

In [ ]:
future_pred=grid.predict([[32,43,2,0,1]])
future_pred

-0.057491291684268475