In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [6]:
dependent=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)
X_train
X_test
Y_train
Y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
1261   3277.16100
494   17942.10600
97    10226.28420
418   14418.28040
920   13451.12200

[402 rows x 1 columns]

In [8]:
#but this code didnt improve the r2_score. so didnt run this while execution

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [9]:
#but this code didnt improve the r2_score. so didnt run this while execution


scy=StandardScaler()
Y_train=scy.fit_transform(Y_train)
Y_test=scy.transform(Y_test)
Y_train

array([[-9.29114569e-01],
       [-6.38651947e-01],
       [-5.39325234e-02],
       [-4.89603748e-01],
       [-6.71349717e-01],
       [-9.67549383e-01],
       [ 1.99311860e+00],
       [-7.49986519e-03],
       [-5.43346082e-01],
       [-2.11871148e-02],
       [-3.93810261e-01],
       [-6.34346126e-02],
       [ 2.99749417e+00],
       [-8.24494558e-01],
       [-4.46162315e-01],
       [ 2.82436277e-01],
       [ 1.14345861e-01],
       [-9.85403479e-01],
       [-5.30554176e-01],
       [-9.27713303e-01],
       [-1.15928290e-01],
       [ 5.03782109e-01],
       [-1.43008068e-01],
       [ 2.33634863e+00],
       [-7.02715735e-01],
       [ 1.74120307e+00],
       [ 2.98421635e-01],
       [-1.89528398e-01],
       [-4.38466738e-01],
       [ 2.63340976e+00],
       [-4.17078733e-01],
       [-7.99784555e-01],
       [-3.51547052e-01],
       [ 4.66138790e-01],
       [ 1.93407799e+00],
       [ 4.94776882e-01],
       [ 1.04631189e+00],
       [ 2.18064123e+00],
       [-7.85495714e-01],
       [ 3.24442330e-01],
       [-8.59972348e-01],
       [ 1.95091150e+00],
       [-7.39736419e-01],
       [-1.54628012e-01],
       [-9.77847424e-01],
       [ 2.41593015e+00],
       [-3.61199865e-01],
       [-7.44605137e-01],
       [-7.77133116e-01],
       [-3.62309921e-01],
       [-3.18826164e-01],
       [-4.63295326e-01],
       [-1.39533403e-01],
       [-7.97983938e-01],
       [-9.33028227e-01],
       [-8.57060133e-01],
       [-7.81289427e-01],
       [-4.80573034e-01],
       [ 1.78603367e+00],
       [-2.56132266e-02],
       [-5.12074006e-01],
       [ 1.09515949e+00],
       [-1.25401058e-01],
       [-9.65438287e-01],
       [-2.02771682e-01],
       [-2.05205910e-01],
       [-7.52638041e-01],
       [-9.77018054e-01],
       [ 2.60824970e+00],
       [-4.72419633e-01],
       [ 1.27232396e+00],
       [-8.11768444e-01],
       [ 9.50008466e-01],
       [-6.52249406e-01],
       [-1.17104791e-01],
       [ 3.80299823e-01],
       [ 1.74062238e+00],
       [-3.08741699e-01],
       [-4.39275703e-01],
       [-9.70365525e-01],
       [-7.57386204e-01],
       [-4.15233239e-01],
       [-9.35022970e-01],
       [-2.84474706e-01],
       [-9.67654741e-01],
       [-8.28764375e-01],
       [ 2.26305468e+00],
       [-5.88059727e-01],
       [-5.02554605e-01],
       [-7.78445380e-01],
       [ 6.70630022e-01],
       [-2.37989487e-01],
       [-3.66949273e-02],
       [-6.98869591e-01],
       [-5.98744310e-01],
       [-7.00524092e-01],
       [-9.85248954e-01],
       [-3.81468006e-01],
       [ 7.11178707e-01],
       [-6.83558909e-01],
       [ 2.77654778e+00],
       [-2.75834631e-01],
       [-5.43800293e-01],
       [-8.57929790e-01],
       [-5.78748559e-01],
       [ 2.23095501e+00],
       [-9.53914846e-01],
       [-1.25913554e-01],
       [-3.70367149e-01],
       [-3.96916353e-01],
       [-9.27702181e-01],
       [-1.09035407e-01],
       [-1.56297651e-02],
       [ 1.88252542e+00],
       [-9.33085934e-02],
       [-4.87568576e-01],
       [ 1.35457935e-02],
       [ 8.60461663e-02],
       [ 1.94335048e+00],
       [-4.38764129e-01],
       [-1.58306087e-01],
       [ 6.08912403e-01],
       [-8.07480119e-01],
       [ 1.88336878e+00],
       [-7.20877173e-01],
       [ 5.15207584e-01],
       [ 4.69373466e-01],
       [-7.43924729e-01],
       [-2.25069753e-01],
       [-2.23451117e-01],
       [-6.59883490e-01],
       [-9.48805728e-01],
       [-1.01788460e+00],
       [-9.76384148e-01],
       [-8.42681118e-01],
       [-9.68626379e-01],
       [ 1.66205560e-02],
       [-8.43817999e-01],
       [-4.95611608e-01],
       [-3.52448452e-01],
       [-1.25454546e-01],
       [-5.61059915e-01],
       [-5.68742363e-02],
       [-9.29481567e-01],
       [-3.41827694e-01],
       [-6.81726609e-01],
       [-4.89459173e-01],
       [-7.32176911e-02],
       [-1.17245181e-01],
       [ 6.32745745e-01],
       [-1.42358809e-02],
       [-4.35426641e-01],
       [-5.03310844e-01],
       [ 1.10827077e+00],
       [-6.60917602e-01],
       [-1.85219705e-01],
       [-5.18431047e-01],
       [-6.70937367e-01],
       [ 7.28320414e-01],
       [-2.12171373e-01],
       [-3.03052929e-01],
       [-2.68595629e-02],
       [-2.49580240e-01],
       [-6.82824913e-01],
       [-8.21019080e-01],
       [-6.86624863e-01],
       [-5.75270491e-01],
       [-9.70898351e-01],
       [-5.04398073e-01],
       [-8.44860373e-01],
       [-6.70815034e-01],
       [-8.39731531e-02],
       [-8.15134509e-01],
       [-7.97222680e-01],
       [-9.27546889e-01],
       [-9.20568907e-01],
       [-7.48363731e-01],
       [ 4.14776662e-01],
       [ 7.71686975e-01],
       [ 1.99745788e+00],
       [-2.32275549e-02],
       [-2.82995007e-01],
       [ 2.62687474e+00],
       [-9.76804377e-01],
       [-6.75407753e-02],
       [-9.78388264e-01],
       [-6.72018877e-01],
       [ 3.32309659e-01],
       [-2.63335421e-01],
       [-6.74169438e-01],
       [ 3.39169186e-02],
       [-2.66764936e-01],
       [ 2.22039905e+00],
       [ 1.42614457e+00],
       [-5.99688901e-01],
       [-1.00100914e-01],
       [ 5.23115516e-01],
       [-9.77036165e-01],
       [-3.89803389e-01],
       [-7.78080137e-01],
       [-9.77873179e-01],
       [ 9.63005841e-01],
       [ 1.69067172e+00],
       [ 6.35735516e-01],
       [ 9.47844387e-02],
       [-5.26152479e-01],
       [ 9.39946882e-01],
       [ 9.80053327e-01],
       [-4.20450292e-01],
       [ 3.32380370e-01],
       [ 2.23529484e+00],
       [-7.48918100e-01],
       [ 8.90562215e-01],
       [-3.90069046e-01],
       [ 9.51912436e-01],
       [ 3.64455944e-01],
       [-5.14358421e-02],
       [-3.09075367e-01],
       [ 3.00115107e-01],
       [-3.42731903e-04],
       [ 1.84669504e+00],
       [-9.28247118e-01],
       [-2.34328798e-01],
       [-1.53382846e-01],
       [-9.28869903e-01],
       [-5.82878808e-01],
       [ 9.80352146e-01],
       [-9.71732438e-01],
       [-9.06164535e-01],
       [-1.86776667e-01],
       [-7.54434982e-03],
       [-5.54089568e-01],
       [-1.01998357e+00],
       [ 3.94049342e+00],
       [-9.47706894e-01],
       [-1.89974340e-01],
       [ 5.84882402e-01],
       [-9.05288494e-01],
       [-7.32426436e-01],
       [ 1.07463028e+00],
       [ 2.71421246e-01],
       [-5.98303957e-01],
       [ 2.81007745e+00],
       [ 1.58970221e+00],
       [-1.32628679e-01],
       [-9.60611565e-01],
       [-2.83533686e-01],
       [ 2.44728292e-01],
       [-6.15879965e-01],
       [-9.43756663e-01],
       [-4.89684253e-01],
       [ 1.49376661e-01],
       [-4.71080592e-01],
       [-1.44252223e-01],
       [-3.48486695e-01],
       [-4.94122628e-02],
       [-7.66297465e-01],
       [-9.77918868e-01],
       [-9.86845718e-01],
       [ 1.81690946e+00],
       [-5.86203348e-01],
       [ 5.45768487e-02],
       [-8.32055767e-01],
       [ 2.39424410e+00],
       [-9.67186482e-01],
       [-4.71005490e-01],
       [-3.65661433e-01],
       [-1.57503696e-01],
       [-4.62431914e-01],
       [-9.68860509e-01],
       [-5.41821392e-01],
       [-1.94460963e-01],
       [-3.95378303e-01],
       [-9.10912743e-01],
       [ 4.56090080e-01],
       [-5.54893593e-02],
       [-1.55939710e-01],
       [-9.32826875e-01],
       [-7.82018628e-01],
       [-5.07859049e-02],
       [-9.47337735e-01],
       [-8.22107311e-01],
       [-6.71683352e-01],
       [ 1.65170000e-02],
       [-9.74241903e-01],
       [-3.41151047e-01],
       [-8.78546945e-01],
       [-9.20425549e-01],
       [-5.07288631e-01],
       [-7.71319357e-01],
       [-8.86307492e-01],
       [-5.08474776e-02],
       [-3.74813587e-01],
       [ 2.91936740e+00],
       [-2.65044083e-01],
       [ 2.10655022e+00],
       [ 1.92463324e-01],
       [ 5.93535570e-02],
       [-5.44286112e-01],
       [-6.99127134e-01],
       [-8.28680901e-01],
       [-3.82697368e-01],
       [ 1.68220276e-01],
       [-7.42625411e-01],
       [-8.86162917e-01],
       [-8.70456443e-01],
       [-2.35546272e-01],
       [-7.97693617e-01],
       [-2.41126749e-03],
       [-3.59160503e-01],
       [-5.58602261e-01],
       [-8.41425350e-02],
       [ 1.16264729e+00],
       [-1.18101510e-01],
       [-1.49817295e-01],
       [ 4.89142308e-01],
       [-9.12747330e-01],
       [-8.69088258e-01],
       [-4.71560377e-01],
       [-1.01833530e+00],
       [-5.74269406e-01],
       [-1.01879888e+00],
       [-5.93629621e-01],
       [ 5.84011987e-01],
       [-4.30234992e-01],
       [-7.48069717e-01],
       [-7.74874506e-01],
       [ 1.45256261e-02],
       [-8.19647880e-01],
       [-9.45359281e-01],
       [-9.76973569e-01],
       [-3.91671487e-01],
       [-4.03431474e-01],
       [-8.82441064e-01],
       [-6.34430665e-01],
       [-7.02634657e-01],
       [-3.96749852e-01],
       [ 2.39546352e+00],
       [-7.25535537e-01],
       [-1.00819412e+00],
       [-1.75356083e-01],
       [-5.51340422e-01],
       [-5.12731653e-01],
       [ 6.73692595e-01],
       [-3.37522340e-01],
       [-8.03409076e-01],
       [-7.64979134e-01],
       [ 3.95526435e-01],
       [ 1.78881165e+00],
       [-3.39792354e-02],
       [-5.08351883e-01],
       [-7.88055383e-01],
       [-9.77574112e-01],
       [ 1.79066076e-01],
       [-7.82340152e-01],
       [-8.55316170e-01],
       [-8.47355812e-01],
       [ 3.93439790e-01],
       [ 1.62426859e-01],
       [ 2.84851714e+00],
       [ 1.96629888e+00],
       [ 1.15953712e+00],
       [-9.56128824e-01],
       [ 3.56758649e-01],
       [-1.60538971e-01],
       [-5.72463264e-01],
       [-5.79146318e-01],
       [-1.00807706e+00],
       [-4.30885873e-01],
       [ 2.77061381e+00],
       [ 3.46963641e-01],
       [-9.44297503e-01],
       [ 1.93370497e-02],
       [ 2.10967949e+00],
       [-6.53871083e-01],
       [ 4.65981953e-01],
       [ 9.63363296e-01],
       [-4.62581218e-01],
       [-3.89858995e-01],
       [-5.29252268e-01],
       [-8.74384410e-01],
       [-9.29193529e-02],
       [ 1.18663461e+00],
       [-8.29351051e-01],
       [-1.13775804e-01],
       [ 8.44008411e-02],
       [ 2.17712731e-01],
       [ 9.68347307e-02],
       [ 4.23311447e-01],
       [ 4.29124440e-01],
       [-5.46105359e-01],
       [-3.32611883e-01],
       [ 2.58245523e+00],
       [-2.43729390e-01],
       [-3.71376597e-01],
       [-1.66711730e-01],
       [-4.95815031e-01],
       [-5.93475702e-01],
       [-7.21896720e-01],
       [ 9.97902012e-01],
       [ 4.22240135e-01],
       [ 4.97875893e-01],
       [-1.46928956e-01],
       [-1.00984474e+00],
       [-6.92320193e-01],
       [-9.34400185e-01],
       [-2.22228699e-01],
       [-4.61838454e-01],
       [-5.11999682e-01],
       [ 2.05281278e+00],
       [-2.83978351e-01],
       [-9.85922076e-01],
       [ 9.46924966e-01],
       [-1.67473418e-01],
       [-6.73093431e-01],
       [-4.95485296e-02],
       [-2.36656228e-01],
       [-3.21878722e-01],
       [-5.53040667e-01],
       [-6.93045995e-01],
       [-9.56309104e-01],
       [ 3.06092919e+00],
       [ 9.78326326e-02],
       [-6.21223158e-02],
       [-6.44160673e-01],
       [-8.12976330e-01],
       [-1.82114261e-01],
       [ 7.58075876e-02],
       [ 2.18625334e-01],
       [-2.40146103e-01],
       [-1.01870874e+00],
       [-9.97273432e-01],
       [-4.21081272e-01],
       [-8.28712867e-01],
       [-7.11932233e-01],
       [-2.55617737e-01],
       [-2.88753308e-02],
       [ 2.42752713e-01],
       [-9.34667093e-01],
       [-7.49145972e-01],
       [-7.39320321e-01],
       [-4.38357135e-01],
       [ 1.22045328e+00],
       [-3.14020615e-01],
       [-6.29215528e-02],
       [ 4.04341208e-01],
       [ 2.57040857e+00],
       [-8.39895321e-01],
       [ 2.62490430e+00],
       [-5.24711062e-02],
       [-4.33644914e-01],
       [-6.70448036e-01],
       [-7.71147272e-01],
       [ 2.00833188e+00],
       [-1.74279087e-01],
       [-2.79823405e-01],
       [-6.72648585e-01],
       [-9.37260045e-01],
       [ 2.38860118e-01],
       [ 6.35073453e-01],
       [-8.47706084e-01],
       [-5.78935285e-01],
       [-1.01648099e+00],
       [-2.05575654e-01],
       [-2.00844693e-01],
       [-7.57619163e-01],
       [-6.94012546e-01],
       [-9.49653893e-02],
       [ 2.68455606e-01],
       [ 9.92116563e-02],
       [ 1.93335393e+00],
       [ 2.00394386e-02],
       [-4.63716747e-01],
       [-1.81100076e-01],
       [-3.92719217e-01],
       [-4.34970088e-01],
       [ 1.02489665e-01],
       [ 3.07569531e-01],
       [ 2.25290928e+00],
       [-2.83772284e-01],
       [-3.59520073e-01],
       [ 1.84563336e+00],
       [-8.92718257e-01],
       [-7.89569213e-01],
       [-7.87923146e-01],
       [-4.12544799e-01],
       [ 2.81532718e+00],
       [ 2.23136498e+00],
       [ 1.81464795e+00],
       [-1.57459212e-01],
       [ 2.48679271e+00],
       [ 2.98478622e+00],
       [ 6.83181116e-01],
       [ 3.20911334e-01],
       [-8.06279438e-01],
       [ 1.31683176e+00],
       [-6.93136135e-01],
       [-2.50002844e-01],
       [-9.32917015e-01],
       [ 2.43214807e+00],
       [-4.92020177e-02],
       [-5.07944779e-01],
       [-9.56954696e-02],
       [-7.29465786e-01],
       [-3.32235869e-01],
       [ 1.92791943e+00],
       [-5.62982583e-01],
       [ 2.71015886e-01],
       [-2.90941418e-01],
       [-9.60169329e-01],
       [ 2.28959463e+00],
       [ 1.02656483e-01],
       [-7.43714012e-01],
       [-3.03778731e-01],
       [ 4.52707858e-01],
       [-5.11448879e-01],
       [-8.96737455e-01],
       [-9.44329110e-01],
       [-3.59373935e-01],
       [ 7.37049796e-01],
       [-9.07522398e-01],
       [-1.32662042e-01],
       [ 9.57584591e-01],
       [ 2.43219615e+00],
       [-1.90055236e-01],
       [-9.07311096e-01],
       [-8.02488854e-01],
       [ 6.75982997e-01],
       [-3.15424222e-01],
       [-9.27368399e-01],
       [ 2.57550628e+00],
       [-4.94766581e-01],
       [ 2.64518355e+00],
       [-7.38291266e-01],
       [-1.04916052e-01],
       [-8.87959580e-01],
       [ 1.91919747e+00],
       [-8.21226512e-01],
       [-2.93420548e-01],
       [-2.66205548e-01],
       [-4.21119903e-01],
       [ 1.32372135e+00],
       [-1.63706090e-01],
       [ 2.40211227e-01],
       [ 1.41746681e+00],
       [ 2.77234856e+00],
       [-7.19782617e-01],
       [ 7.19351239e-01],
       [-1.01112893e-01],
       [-7.66334589e-01],
       [-6.10858229e-01],
       [-1.94046958e-01],
       [-2.68631573e-01],
       [-7.38578985e-01],
       [-2.89043031e-01],
       [-9.77318325e-01],
       [-7.23120203e-01],
       [-2.12944001e-01],
       [-8.69886741e-01],
       [-2.58578921e-02],
       [ 3.81834810e+00],
       [-3.21549004e-01],
       [ 3.24089653e-01],
       [ 1.72795906e+00],
       [-2.44885351e-01],
       [-1.91449154e-01],
       [-1.65775211e-01],
       [-9.05520678e-01],
       [ 7.09717220e-01],
       [ 7.46775541e-02],
       [ 5.52911358e-01],
       [-8.13130426e-01],
       [-9.42180823e-01],
       [ 2.11488564e+00],
       [-5.01223679e-01],
       [ 7.56727155e-01],
       [ 9.15800378e-01],
       [ 2.17406814e+00],
       [-9.47896808e-01],
       [ 1.16939154e+00],
       [-1.01368861e-01],
       [-5.84748232e-01],
       [ 2.14574645e+00],
       [ 5.35794214e-01],
       [-3.95261865e-01],
       [ 2.07152602e+00],
       [-3.04249458e-01],
       [-6.97367305e-02],
       [-6.75719907e-01],
       [ 5.66950021e-01],
       [-5.77690448e-01],
       [ 5.51036404e-02],
       [ 6.30746901e-02],
       [ 5.22954463e-01],
       [-9.28536268e-01],
       [-7.88803158e-01],
       [ 7.66281995e-01],
       [-7.47519828e-01],
       [ 4.14826705e-02],
       [-1.09635950e-01],
       [ 3.15361105e-02],
       [-3.34192258e-01],
       [-7.14119029e-01],
       [ 1.04580039e-01],
       [ 6.43929676e-01],
       [ 8.46910323e-01],
       [-6.33670207e-01],
       [ 1.80559708e+00],
       [ 1.15326528e+00],
       [-3.94278521e-01],
       [-5.26052254e-01],
       [-4.72325981e-01],
       [-9.09135699e-01],
       [-6.11308491e-01],
       [ 5.03798807e-02],
       [ 2.04244721e+00],
       [-2.82744084e-01],
       [-4.30119098e-01],
       [-8.86296371e-01],
       [-1.80414480e-01],
       [-9.70264445e-01],
       [-2.59069802e-01],
       [ 1.32765443e-02],
       [ 5.15321692e-02],
       [-6.04167679e-01],
       [-1.31279911e-01],
       [-6.80557872e-01],
       [-9.18274959e-02],
       [-6.10033499e-01],
       [-6.41544543e-01],
       [-7.13386978e-01],
       [-9.56526844e-01],
       [-1.54866744e-01],
       [-9.24903237e-01],
       [-8.94737605e-03],
       [-6.15312167e-01],
       [-4.14147598e-02],
       [-5.37646810e-01],
       [-5.11287330e-01],
       [ 3.52899816e+00],
       [-7.40679557e-01],
       [-7.89278622e-01],
       [-3.10209287e-01],
       [-6.53110566e-01],
       [-1.63922580e-01],
       [-2.84870486e-01],
       [-1.74123311e-01],
       [-3.47919921e-01],
       [-3.96284203e-01],
       [ 1.54854746e+00],
       [-4.19465373e-01],
       [-3.71317075e-01],
       [ 1.35576797e+00],
       [-9.04168183e-01],
       [-5.20996973e-01],
       [ 2.97431098e+00],
       [-2.64107228e-01],
       [-7.57804407e-01],
       [-9.14575711e-02],
       [-7.16974085e-01],
       [ 2.88282487e+00],
       [ 2.23118846e+00],
       [ 7.21261185e-01],
       [-1.00979791e+00],
       [-2.82581768e-01],
       [ 6.83506143e-01],
       [ 5.31114429e-01],
       [-1.90964784e-01],
       [-7.33190815e-01],
       [-9.12669482e-01],
       [-1.57234447e-01],
       [-8.14762491e-01],
       [-6.91000005e-01],
       [-9.18108104e-01],
       [ 5.89698366e-01],
       [ 8.48394149e-01],
       [ 2.41846912e+00],
       [-3.44318114e-01],
       [ 1.95580155e-01],
       [-4.22933869e-01],
       [ 2.86656718e+00],
       [-6.31974173e-01],
       [-8.35718582e-01],
       [-5.00870278e-02],
       [-5.82726624e-01],
       [ 2.76918078e+00],
       [-1.62289075e-01],
       [-4.81304150e-01],
       [-9.68974794e-01],
       [-9.06898531e-01],
       [-7.14673521e-01],
       [-1.17089485e-01],
       [ 5.46311946e-01],
       [-4.12533678e-01],
       [-8.37172439e-01],
       [ 3.73110695e-01],
       [ 6.61057825e-01],
       [-1.49711305e-01],
       [ 4.81928433e-01],
       [-2.24699794e-01],
       [ 2.31498944e+00],
       [ 1.01708053e+00],
       [ 2.15262596e+00],
       [-8.58085486e-01],
       [-3.84185321e-01],
       [-5.70758753e-01],
       [-9.61535206e-01],
       [-8.85451163e-01],
       [ 4.82598124e-01],
       [-7.10580134e-01],
       [-6.02211097e-01],
       [-6.99862461e-01],
       [-1.00822924e+00],
       [ 8.69993805e-01],
       [ 2.71260635e-02],
       [-3.97185602e-01],
       [-8.47321863e-01],
       [ 2.00381042e-01],
       [-5.20666851e-01],
       [-9.68954161e-01],
       [-2.60387581e-01],
       [ 4.52410462e-02],
       [ 9.22034371e-01],
       [ 1.81877798e+00],
       [ 9.40677349e-02],
       [-5.58589203e-01],
       [ 1.00375373e-02],
       [ 4.87658700e-01],
       [ 1.40528350e-01],
       [ 4.69256142e-01],
       [ 5.27533102e-01],
       [ 1.08705593e+00],
       [ 5.16187046e-01],
       [-6.72717653e-01],
       [ 7.36561854e-01],
       [-1.08330496e-01],
       [-9.34500275e-01],
       [-1.42709228e-01],
       [ 5.64314942e-01],
       [-9.71087410e-01],
       [-8.88679327e-01],
       [-1.01876024e+00],
       [-5.92412450e-01],
       [ 1.80102342e+00],
       [-8.16524127e-01],
       [-9.58784950e-02],
       [-6.61926015e-01],
       [-8.49406940e-02],
       [ 2.88434354e-01],
       [-3.10872055e-01],
       [ 2.44052566e+00],
       [ 7.77270673e-01],
       [-5.49339321e-01],
       [ 9.83875540e-01],
       [-2.97146625e-01],
       [-5.76358057e-01],
       [-5.91978725e-01],
       [-2.42322136e-01],
       [-1.86899863e-01],
       [-3.07318190e-01],
       [-6.40273771e-01],
       [-1.13827313e-01],
       [-7.07634715e-01],
       [-8.83542059e-01],
       [ 6.52798741e-01],
       [-9.01967432e-01],
       [-6.97601779e-01],
       [-4.04660883e-01],
       [-1.47407499e-01],

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','linear'],
             'C':[50,1000,15000],
             'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid,cv=3, refit=True,verbose = 3, n_jobs=-1)

grid.fit(X_train,Y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

C:\Users\subas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=3, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [50, 1000, 15000], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear']},
             verbose=3)

In [11]:
re= grid.cv_results_
#print(re)

print("R2 value for best parameter {}:".format(grid.best_params_))

R2 value for best parameter {'C': 50, 'gamma': 'auto', 'kernel': 'rbf'}:

In [12]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.215526,0.022835,0.017315,0.000750,50,auto,rbf,"{'C': 50, 'gamma': 'auto', 'kernel': 'rbf'}",0.813193,0.776983,0.744346,0.778174,0.028119,1
1,0.873149,0.105852,0.004669,0.000604,50,auto,linear,"{'C': 50, 'gamma': 'auto', 'kernel': 'linear'}",0.703966,0.652125,0.653287,0.669793,0.024169,7
2,0.197112,0.018016,0.015804,0.002497,50,scale,rbf,"{'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}",0.813245,0.776822,0.744162,0.778076,0.028217,2
3,0.875479,0.109797,0.004457,0.000684,50,scale,linear,"{'C': 50, 'gamma': 'scale', 'kernel': 'linear'}",0.703966,0.652125,0.653287,0.669793,0.024169,7
4,1.994022,0.172497,0.016888,0.001032,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731025,0.623780,0.523825,0.626210,0.084607,9
5,12.773365,0.794608,0.004173,0.000293,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.703838,0.652549,0.653029,0.669806,0.024066,5
6,1.825953,0.154586,0.018371,0.001304,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.730642,0.622609,0.523560,0.625603,0.084567,10
7,12.665474,0.816689,0.004405,0.000564,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.703838,0.652549,0.653029,0.669806,0.024066,5
8,28.007041,2.443607,0.023422,0.000608,15000,auto,rbf,"{'C': 15000, 'gamma': 'auto', 'kernel': 'rbf'}",0.424064,-0.294940,-0.618621,-0.163166,0.435753,12
9,211.928743,10.836006,0.004500,0.002469,15000,auto,linear,"{'C': 15000, 'gamma': 'auto', 'kernel': 'linear'}",0.704059,0.655454,0.650599,0.670037,0.024139,3
10,37.865109,5.700827,0.018940,0.006080,15000,scale,rbf,"{'C': 15000, 'gamma': 'scale', 'kernel': 'rbf'}",0.423713,-0.289644,-0.621915,-0.162615,0.436224,11
11,202.132231,10.616093,0.004656,0.001099,15000,scale,linear,"{'C': 15000, 'gamma': 'scale', 'kernel': 'line...",0.704059,0.655454,0.650599,0.670037,0.024139,3

In [13]:
'''
future_pred=grid.predict([[32,43,2,0,1]])
future_pred
'''
import pickle
filename='svr_final_input_output_process_model.sav'

pickle.dump(grid,open(filename,'wb'))